# Generated by Django 4.0.2 on 2022-02-18 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reservation', models.BooleanField(default=False)),
                ('reserved_date', models.DateTimeField()),
                ('persons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_cost', models.FloatField()),
                ('percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('total', models.FloatField()),
                ('total_after_percent', models.FloatField()),
                ('order_items',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_items.orderitems')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
