# Generated by Django 4.0.2 on 2022-02-18 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мерчанта')),
                ('percent', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('reservation_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
    ]
